name: MacOS Workflow
on: [push]

jobs:
  k6_local_test:
    name: k6 local test run on windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: download and extract k6 release binaries
        run: winget install k6
        shell: bash
        
      - name: k6 test
        run: k6 run test-types/smoke-test.js -e BASE_URL=https://test-api.k6.io -e USERNAME=cvenkatreddy -e PASSWORD=Deveshi#7
        shell: bash
